title: "Guida Klipper"
remote_theme: pmarsceill/just-the-docs
logo: "/images/title.png"
search_enabled: true

baseurl: "/"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
